-- Atividade 1 
-- INNER JOIN
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
INNER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- LEFT OUTER JOIN
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
LEFT OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- RIGHT OUTER JOIN
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
RIGHT OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;

-- FULL OUTER JOIN
SELECT A.CODIGO, A.NOME, B.ID, B.VALOR
FROM TABELA_A A
FULL OUTER JOIN TABELA_B B ON A.CODIGO = B.CODIGO;


-- Atividade 2
-- A)
SELECT SUM(VALOR_TOTAL) AS VALOR_TOTAL_GERAL
FROM PEDIDO;

-- B)
SELECT AVG(VALOR_TOTAL) AS MEDIA_VALOR
FROM PEDIDO;

-- C)
SELECT MAX(VALOR_TOTAL) AS MAIOR_VALOR
FROM PEDIDO;

-- D)
SELECT MIN(VALOR_TOTAL) AS MENOR_VALOR
FROM PEDIDO;

-- E)
SELECT COUNT(*) AS TOTAL_PEDIDOS
FROM PEDIDO;


-- ATIVIDADE 3 
-- A)
SELECT *
FROM PEDIDO
WHERE VALOR_TOTAL > 100;

-- B)
SELECT *
FROM PEDIDO
WHERE DATA_PEDIDO = '2022-06-10';

-- C)
SELECT *
FROM PEDIDO
WHERE DATA_PEDIDO BETWEEN '2022-06-10' AND '2022-06-15';

-- D)
SELECT *
FROM PEDIDO
WHERE VALOR_TOTAL BETWEEN 50 AND 150;

-- E)
SELECT *
FROM PEDIDO
WHERE VALOR_TOTAL < 80
  AND DATA_PEDIDO > '2022-06-10';
